spring:
  mail:
    host: email-smpt.us-east-1.amazonaws.com
    port: 587
    username:
    password:

    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8087

